### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by sondreb** [CityChainFoundation/city-hub#55]
This is a log entry after startup on an instance of City Hub that has been running for a while and PC might have crashed.

```
[2018-08-18 22:12:04.8561 1] INFO: Stratis.Bitcoin.FullNode.Initialize Full node initialized on CityTest
[2018-08-18 22:12:04.9456 1] INFO: Stratis.Bitcoin.FullNode.Start Starting node...
[2018-08-18 22:12:05.1470 1] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__26.MoveNext Loading finalized block height
[2018-08-18 22:12:05.1718 8] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__26.MoveNext Loading chain
[2018-08-18 22:12:05.8983 6] INFO: Stratis.Bitcoin.Base.BaseFeature+<StartChainAsync>d__26.MoveNext Chain loaded at height 24969
[2018-08-18 22:12:05.9104 7] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext FlushChain starting
[2018-08-18 22:12:06.2367 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Periodic peer flush... starting
[2018-08-18 22:12:06.3342 8] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext Consensus Loop starting
[2018-08-18 22:12:06.6852 1] INFO: Stratis.Bitcoin.Features.MemoryPool.MempoolManager+<LoadPoolAsync>d__25.MoveNext Loading Memory Pool...
[2018-08-18 22:12:06.6942 6] INFO: Stratis.Bitcoin.Utilities.AsyncLoop+<>c__DisplayClass16_0+<<StartAsync>b__0>d.MoveNext MemoryPool.RelayWorker starting
[2018-08-18 22:12:06.9422 1] INFO: Stratis.Bitcoin.Features.Api.ApiFeature.Initialize API starting on URL 'http://localhost:24335/'.
[2018-08-18 22:12:07.8721 1] WARN: Stratis.Bitcoin.Features.RPC.RPCFeature.Initialize RPC Server is off based on configuration.
[2018-08-18 22:12:07.8991 1] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize An error occurred starting the application: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Wallet.WalletManager.Start() in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 161
   at Stratis.Bitcoin.Features.Wallet.WalletFeature.Initialize() in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletFeature.cs:line 144
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 118
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 56
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Wallet.WalletManager.Start() in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 161
   at Stratis.Bitcoin.Features.Wallet.WalletFeature.Initialize() in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletFeature.cs:line 144
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in D:\a\1\s\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 102<---
```

This makes the UI simply halt and keep loading and loading and nothing happens.

**Comment by sondreb** [comment]
Recent improvements to how shutdown is executed, have greatly improved this. Closing this issue.
