### ISSUE TITLE
Bug: Receive address not generated

### ISSUE THREAD

**Issue by sondreb** [CityChainFoundation/city-hub#90]
User reported issue that receive address was not being shown. Received screenshot and log.

Screenshot:
![image](https://user-images.githubusercontent.com/309938/46509999-876af600-c846-11e8-92e3-0f8008c706af.png)

Exception from log:

```
[2018-10-05 00:22:50.4421 9] ERROR: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.GetUnusedAddress Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stratis.Bitcoin.Features.Wallet.WalletManager.GetUnusedAddresses(WalletAccountReference accountReference, Int32 count, Boolean isChange) in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 489
   at Stratis.Bitcoin.Features.Wallet.WalletManager.GetUnusedAddress(WalletAccountReference accountReference) in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\WalletManager.cs:line 439
   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.GetUnusedAddress(GetUnusedAddressModel request) in D:\a\1\s\src\Stratis.Bitcoin.Features.Wallet\Controllers\WalletController.cs:line 894
[2018-10-05 00:22:50.4634 20] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__76_0
```

**Comment by sondreb** [comment]
This issue is being closed, new address works fine and not able to reproduce a similar issue.
